FROM node:20-alpine

# Pour installer openssl sur Alpine Linux (pour la génération des modèles Prisma)
RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./

# 2. Config npm stable
# Pour éviter les erreurs de timeout lors de l'installation des dépendances
ENV NPM_CONFIG_FETCH_TIMEOUT=600000
ENV NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000

# RUN npm ci
# RUN npm ci --no-audit --no-fund
# RUN npm ci --legacy-peer-deps
RUN npm install --legacy-peer-deps

# 4. Copier le reste du code
COPY . .

# RUN npm run build
# RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
# CMD ["sh", "-c", "npx prisma generate && npm run start:dev"]