FROM node:20-alpine
# FROM node:20

WORKDIR /app

COPY package*.json ./

# 2. Config npm stable
# Pour éviter les erreurs de timeout lors de l'installation des dépendances
ENV NPM_CONFIG_FETCH_TIMEOUT=600000
ENV NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000

# RUN npm ci
# RUN npm ci --no-audit --no-fund
# RUN npm ci --legacy-peer-deps
RUN npm install --legacy-peer-deps

# 4. Copier le reste du code
COPY . .

# RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:dev"]